### ISSUE TITLE
displays 'on hold' even for active repositories

### ISSUE THREAD

**Issue by kybernetyk** [icebreaker/proudify#1]
hello,

the github module shows even active repos as 'on hold'. 

See 
  http://jsz.github.com/proud.html 
he 6502 repository was updated yesterday and the 'pushed_at' value is set to 360.

**Comment by icebreaker** [comment]
Except the last three which are from 2008-2009 they all show up as ONGOING :)

**Comment by kybernetyk** [comment]
Hmm, I should have tried a different browser. With Chrome everything works like you describe.

But with Safari 5 the bugs I mentioned occur.

**Comment by icebreaker** [comment]
Thanks, I'll take a look :)

**Comment by icebreaker** [comment]
This appears to be a Safari 5 only bug due to the way Safari parses 'dates'. I'll close it for now.
