### ISSUE TITLE
Strange layout in Firefox

### ISSUE THREAD

**Issue by arruda** [icebreaker/proudify#15]
Hi, I was testing this repository and then I saw that if I visualize the page in firefox(9.0.1 Ubuntu) it gets messed up.
And not only in the page that I was testing, but in your page as whell:http://proudify.me/
I don't know if this is a css thing related to the proudfy.css or related to the main.css that is on your page.

**Comment by icebreaker** [comment]
That's a Firefox 'mime-type' issue, because the 'css' from the repo is being served as 'raw' with the content type text and Firefox doesn't know what to do with it, even though the element has the 'text/css' attribute.

**Comment by icebreaker** [comment]
I'm going to close this mainly because I don't care about FF. The workaround is to keep a 'local' copy of proudify.css. Not the most elegant solution but it works.
