### ISSUE TITLE
Uncaught TypeError: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by jwarchol** [icebreaker/proudify#2]
I'm getting this error:

Uncaught TypeError: Cannot read property '0' of undefined 

From this line: 

https://github.com/icebreaker/proudify/blob/master/jquery-proudify.js#L52

As seen here:

http://unwin.org/

**Comment by KristianOellegaard** [comment]
I solved it like this:

```
    fetch : function(url)
    {
        var self = this;
        $.getJSON(url, function(result)
        {
            for(var i in result.data)
                self.repositories.push(result.data[i]);

            if (result.meta["Link"] === undefined)
            {
                self.render();
            } else {
                if(result.meta['Link'][0][1]['rel'] == 'first')
                {
                    self.render();
                } else {
                    self.fetch(result.meta['Link'][0][0]+'&callback=?');
                }
            }
        });
    },
```

However, I usually don't do javascript, so I have no idea if it can be done a bit smarter - but it works :-)

It seems that if you have less than a certain amount of repositories, you will get this error, as there will be no pagination i think. Correct me, if I'm wrong.
