### ISSUE TITLE
feature request: reverse repo sort order

### ISSUE THREAD

**Issue by kybernetyk** [icebreaker/proudify#3]
I tried to implement this myself but as I've never done anything with jquery/javascript I failed miserably:

It would be nice if you could change the repository sort order. Currently the recently updated repos are at the end of the repo list. There should be a way (settings parameter) to reverse the sort order so that those repos show up on the top.

**Comment by icebreaker** [comment]
They are sorted by pushed_at in reverse order so the most recent ones show up first.
