### ISSUE TITLE
Loading the css from Github doesn't work.

### ISSUE THREAD

**Issue by lavelle** [icebreaker/proudify#8]
If I save a copy of the CSS file and import it locally, it works, but this is not the case if I reference the file hosted here.
Chrome's Dev Tools tell me the file has been successfully imported, but none of the styles apply.
I'm importing it after everything else.

```
<link rel="stylesheet" href="https://raw.github.com/icebreaker/proudify/master/proudify.css" type="text/css">
```

I realise this probably isn't an issue specific to this project, but others may have the same problem so I felt it was a relevant question to ask here

**Comment by icebreaker** [comment]
If you are testing on localhost then use a local copy of the css.
